<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'ncons' => 1,
                'name' => 'BISTEC DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 269.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1000',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 2,
                'name' => 'BISTEC EN FAJITAS SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 269.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1001',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 3,
                'name' => 'MOLIDA DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 226.57,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1002',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 4,
                'name' => 'COCIDO DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 221.57,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1003',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 5,
                'name' => 'CHAMBRETE DE RES SIN HUESO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 264.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1004',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 6,
                'name' => 'CHAMBRETE DE RES CON HUESO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 221.23,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1005',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 7,
                'name' => 'DESHEBRADA DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 269.23,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1006',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 8,
                'name' => 'MENUDO DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 142.40,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1007',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 9,
                'name' => 'COCIDO DE RES SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 211.57,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1008',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 10,
                'name' => 'PIERNA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 234.03,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1009',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 11,
                'name' => 'MACIZA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 279.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1010',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 12,
                'name' => 'DESHEBRADA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 255.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1011',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 13,
                'name' => 'CHICHARRON DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 325.40,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1012',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 14,
                'name' => 'CHULETA DE CERDO AHUMADA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 158.26,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1013',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 15,
                'name' => 'CARNE AL PASTOR SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 218.73,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1014',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 16,
                'name' => 'ADOBADA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 190.57,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1015',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 17,
                'name' => 'CABEZA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 80.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1016',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 18,
                'name' => 'ESPINAZO DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 168.61,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1017',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 19,
                'name' => 'COSTILLA DE CERDO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 161.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '',
                'barcode' => '1018',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 20,
                'name' => 'PECHUGA A PLANADA DE POLLO PARA ASAR SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 209.20,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1019',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 21,
                'name' => 'PECHUGA DE POLLO EN FAJITAS SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 209.20,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1020',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 22,
                'name' => 'PECHUGA DE POLLO ENTERA SIN HUESO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 181.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1021',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 23,
                'name' => 'PECHUGA DE POLLO ENTERA CON HUESO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 176.57,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1022',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 24,
                'name' => 'PIERNA Y MUSLO DE POLLO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 156.81,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1023',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 25,
                'name' => 'RETAZO DE POLLO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 79.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1024',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 26,
                'name' => 'CHORIZO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 163.23,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1025',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 27,
                'name' => 'TOCINO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 315.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1026',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 28,
                'name' => 'FILETE DE PESCADO TILAPIA (SIN HIELO) SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 731.23,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1027',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 29,
                'name' => 'QUESO RANCHERO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 236.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1028',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 30,
                'name' => 'QUESO OAXACA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 254.18,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1029',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 31,
                'name' => 'QUESO PANELA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 236.83,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1030',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 32,
                'name' => 'QUESO AMARILLO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 253.06,
                'unit_of_measure' => 'PAQUETE',
                'unit_of_measure_2' => '1 PAQUETE CON 100 PZAS C/U',
                'barcode' => '1031',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 33,
                'name' => 'JAMON DE PAVO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 187.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 PAQUETE DE 1KG',
                'barcode' => '1032',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 34,
                'name' => 'SALCHICA DE PAVO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 245.76,
                'unit_of_measure' => 'PAQUETE',
                'unit_of_measure_2' => '1 PAQUETE DE 32 PZAS',
                'barcode' => '1033',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 35,
                'name' => 'MANTEQUILLA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 335.80,
                'unit_of_measure' => 'PIEZA',
                'unit_of_measure_2' => '1 PZA DE 1 KG',
                'barcode' => '1034',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 36,
                'name' => 'YOGURTH SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 265.29,
                'unit_of_measure' => 'LT',
                'unit_of_measure_2' => '1 CUBETA DE 4 LT',
                'barcode' => '1035',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 37,
                'name' => 'CREMA LALA',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 110.03,
                'unit_of_measure' => 'BOTE',
                'unit_of_measure_2' => '1 BOTE DE 900 ML',
                'barcode' => '1036',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 38,
                'name' => 'AZUCAR SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 1087.90,
                'unit_of_measure' => 'BULTO',
                'unit_of_measure_2' => '1 BULTO DE 50 KG',
                'barcode' => '1037',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 39,
                'name' => 'SAL SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 539.90,
                'unit_of_measure' => 'BULTO',
                'unit_of_measure_2' => '1 BULTO DE 20 KG',
                'barcode' => '1038',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 40,
                'name' => 'FRIJOL PERUANO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 2144.08,
                'unit_of_measure' => 'BULTO',
                'unit_of_measure_2' => '1 BULTO DE 25 KG',
                'barcode' => '1039',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 41,
                'name' => 'FRIJOL FLOR DE JUNIO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 2144.08,
                'unit_of_measure' => 'BULTO',
                'unit_of_measure_2' => '1 BULTO DE 25 KG',
                'barcode' => '1040',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 42,
                'name' => 'CONDIMENTO DE CALDO DE POLLO A GRANEL SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 305.33,
                'unit_of_measure' => 'BULTO',
                'unit_of_measure_2' => '1 BULTO DE 5 KG',
                'barcode' => '1041',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 43,
                'name' => 'AJO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 1542.82,
                'unit_of_measure' => 'CAJA',
                'unit_of_measure_2' => '1 CAJA DE 10 KG',
                'barcode' => '1042',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 44,
                'name' => 'CANELA MOLIDA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 235.65,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1043',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 45,
                'name' => 'CANELA EN VARA SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 819.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1044',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 46,
                'name' => 'SALSA DE TOMATE AGRIDULCE MARCA LA COSTEÑA',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 514.90,
                'unit_of_measure' => 'CAJA',
                'unit_of_measure_2' => '1 CAJA DE 12 LT',
                'barcode' => '1045',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 47,
                'name' => 'PILONCILLO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 74.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1046',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 48,
                'name' => 'ACEITE VEGETAL MARCA LA PATRONA',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 1588.97,
                'unit_of_measure' => 'BIDON',
                'unit_of_measure_2' => '1 BIDON DE 20 LT',
                'barcode' => '1047',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 49,
                'name' => 'ARROZ SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 53.90,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1049',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ncons' => 50,
                'name' => 'GARBANZO SIN MARCA A GRANEL',
                'category_id' => 3,
                'quantity' => 1,
                'price' => 114.81,
                'unit_of_measure' => 'KG',
                'unit_of_measure_2' => '1 KG',
                'barcode' => '1050',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],













            // Agregar más productos según sea necesario
        ]);
    }
}
