<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SedesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sedes')->insert([
            [                
                'nombre_sede' => 'IEEESSPP',             
                'direccion' => ''
            ],
            ['nombre_sede' => 'Acuitzio', 'direccion' => ""],
            ['nombre_sede' => 'Aguililla', 'direccion' => ""],
            ['nombre_sede' => 'Álvaro Obregón', 'direccion' => ""],
            ['nombre_sede' => 'Angamacutiro', 'direccion' => ""],
            ['nombre_sede' => 'Angangueo', 'direccion' => ""],
            ['nombre_sede' => 'Apatzingán', 'direccion' => ""],
            ['nombre_sede' => 'Aporo', 'direccion' => ""],
            ['nombre_sede' => 'Aquila', 'direccion' => ""],
            ['nombre_sede' => 'Ario', 'direccion' => ""],
            ['nombre_sede' => 'Arteaga', 'direccion' => ""],
            ['nombre_sede' => 'Briseñas', 'direccion' => ""],
            ['nombre_sede' => 'Buenavista', 'direccion' => ""],
            ['nombre_sede' => 'Carácuaro', 'direccion' => ""],
            ['nombre_sede' => 'Coahuayana', 'direccion' => ""],
            ['nombre_sede' => 'Coalcomán de Vázquez Pallares', 'direccion' => ""],
            ['nombre_sede' => 'Coeneo', 'direccion' => ""],
            ['nombre_sede' => 'Contepec', 'direccion' => ""],
            ['nombre_sede' => 'Copándaro', 'direccion' => ""],
            ['nombre_sede' => 'Cotija', 'direccion' => ""],
            ['nombre_sede' => 'Cuitzeo', 'direccion' => ""],
            ['nombre_sede' => 'Charapan', 'direccion' => ""],
            ['nombre_sede' => 'Charo', 'direccion' => ""],
            ['nombre_sede' => 'Chavinda', 'direccion' => ""],
            ['nombre_sede' => 'Cherán', 'direccion' => ""],
            ['nombre_sede' => 'Chilchota', 'direccion' => ""],
            ['nombre_sede' => 'Chinicuila', 'direccion' => ""],
            ['nombre_sede' => 'Chucándiro', 'direccion' => ""],
            ['nombre_sede' => 'Churintzio', 'direccion' => ""],
            ['nombre_sede' => 'Churumuco', 'direccion' => ""],
            ['nombre_sede' => 'Ecuandureo', 'direccion' => ""],
            ['nombre_sede' => 'Epitacio Huerta', 'direccion' => ""],
            ['nombre_sede' => 'Erongarícuaro', 'direccion' => ""],
            ['nombre_sede' => 'Gabriel Zamora', 'direccion' => ""],
            ['nombre_sede' => 'Hidalgo','direccion' => ""],
            ['nombre_sede' => 'La Huacana', 'direccion' => ""],
            ['nombre_sede' => 'Huandacareo', 'direccion' => ""],
            ['nombre_sede' => 'Huaniqueo', 'direccion' => ""],
            ['nombre_sede' => 'Huetamo', 'direccion' => ""],
            ['nombre_sede' => 'Huiramba', 'direccion' => ""],
            ['nombre_sede' => 'Indaparapeo', 'direccion' => ""],
            ['nombre_sede' => 'Irimbo', 'direccion' => ""],
            ['nombre_sede' => 'Ixtlán', 'direccion' => ""],
            ['nombre_sede' => 'Jacona', 'direccion' => ""],
            ['nombre_sede' => 'Jiménez', 'direccion' => ""],
            ['nombre_sede' => 'Jiquilpan', 'direccion' => ""],
            ['nombre_sede' => 'Juárez', 'direccion' => ""],
            ['nombre_sede' => 'Jungapeo', 'direccion' => ""],
            ['nombre_sede' => 'Lagunillas', 'direccion' => ""],
            ['nombre_sede' => 'Madero', 'direccion' => ""],
            ['nombre_sede' => 'Maravatío', 'direccion' => ""],
            ['nombre_sede' => 'Marcos Castellanos', 'direccion' => ""],
            ['nombre_sede' => 'Lázaro Cárdenas', 'direccion' => ""],
            ['nombre_sede' => 'Morelia', 'direccion' => ""],
            ['nombre_sede' => 'Morelos', 'direccion' => ""],
            ['nombre_sede' => 'Múgica', 'direccion' => ""],
            ['nombre_sede' => 'Nahuatzen', 'direccion' => ""],
            ['nombre_sede' => 'Nocupétaro', 'direccion' => ""],
            ['nombre_sede' => 'Nuevo Parangaricutiro', 'direccion' => ""],
            ['nombre_sede' => 'Nuevo Urecho', 'direccion' => ""],
            ['nombre_sede' => 'Numarán', 'direccion' => ""],
            ['nombre_sede' => 'Ocampo', 'direccion' => ""],
            ['nombre_sede' => 'Pajacuarán', 'direccion' => ""],
            ['nombre_sede' => 'Panindícuaro', 'direccion' => ""],
            ['nombre_sede' => 'Parácuaro', 'direccion' => ""],
            ['nombre_sede' => 'Paracho', 'direccion' => ""],
            ['nombre_sede' => 'Pátzcuaro', 'direccion' => ""],
            ['nombre_sede' => 'Penjamillo', 'direccion' => ""],
            ['nombre_sede' => 'Peribán', 'direccion' => ""],
            ['nombre_sede' => 'La Piedad', 'direccion' => ""],
            ['nombre_sede' => 'Purépero', 'direccion' => ""],
            ['nombre_sede' => 'Puruándiro', 'direccion' => ""],
            ['nombre_sede' => 'Queréndaro', 'direccion' => ""],
            ['nombre_sede' => 'Quiroga', 'direccion' => ""],
            ['nombre_sede' => 'Cojumatlán de Régules', 'direccion' => ""],
            ['nombre_sede' => 'Los Reyes', 'direccion' => ""],
            ['nombre_sede' => 'Sahuayo', 'direccion' => ""],
            ['nombre_sede' => 'San Lucas', 'direccion' => ""],
            ['nombre_sede' => 'Santa Ana Maya', 'direccion' => ""],
            ['nombre_sede' => 'Salvador Escalante', 'direccion' => ""],
            ['nombre_sede' => 'Senguio', 'direccion' => ""],
            ['nombre_sede' => 'Susupuato', 'direccion' => ""],
            ['nombre_sede' => 'Tacámbaro', 'direccion' => ""],
            ['nombre_sede' => 'Tancítaro', 'direccion' => ""],
            ['nombre_sede' => 'Tangamandapio', 'direccion' => ""],
            ['nombre_sede' => 'Tangancícuaro', 'direccion' => ""],
            ['nombre_sede' => 'Tanhuato', 'direccion' => ""],
            ['nombre_sede' => 'Taretan', 'direccion' => ""],
            ['nombre_sede' => 'Tarímbaro', 'direccion' => ""],
            ['nombre_sede' => 'Tepalcatepec', 'direccion' => ""],
            ['nombre_sede' => 'Tingambato', 'direccion' => ""],
            ['nombre_sede' => 'Tingüindín', 'direccion' => ""],
            ['nombre_sede' => 'Tiquicheo de Nicolás Romero', 'direccion' => ""],
            ['nombre_sede' => 'Tlalpujahua', 'direccion' => ""],
            ['nombre_sede' => 'Tlazazalca', 'direccion' => ""],
            ['nombre_sede' => 'Tocumbo', 'direccion' => ""],
            ['nombre_sede' => 'Tumbiscatío', 'direccion' => ""],
            ['nombre_sede' => 'Turicato', 'direccion' => ""],
            ['nombre_sede' => 'Tuxpan', 'direccion' => ""],
            ['nombre_sede' => 'Tuzantla', 'direccion' => ""],
            ['nombre_sede' => 'Tzintzuntzan', 'direccion' => ""],
            ['nombre_sede' => 'Tzitzio', 'direccion' => ""],
            ['nombre_sede' => 'Uruapan', 'direccion' => ""],
            ['nombre_sede' => 'Venustiano Carranza', 'direccion' => ""],
            ['nombre_sede' => 'Villamar', 'direccion' => ""],
            ['nombre_sede' => 'Vista Hermosa', 'direccion' => ""],
            ['nombre_sede' => 'Yurécuaro', 'direccion' => ""],
            ['nombre_sede' => 'Zacapu', 'direccion' => ""],
            ['nombre_sede' => 'Zamora', 'direccion' => ""],
            ['nombre_sede' => 'Zináparo', 'direccion' => ""],
            ['nombre_sede' => 'Zinapécuaro', 'direccion' => ""],
            ['nombre_sede' => 'Ziracuaretiro', 'direccion' => ""],
            ['nombre_sede' => 'Zitácuaro', 'direccion' => ""],
            ['nombre_sede' => 'José Sixto Verduzco', 'direccion' => ""],
            
        ]);
    }
}
